include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
